[package]
name = "datagen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bernt = { path = "../" }
chrono = "0.4"
fastrand = "2"
bytemuck = "1.14.0"
